### ISSUE TITLE
Getting error when opening Houdini

### ISSUE THREAD

**Issue by MostHated** [anvdev/Hammer-Tools#155]
Hey there, currently I am getting the following error each time I open Houdini. I tried in v18.348, 353 and 355 and it did it in all of them.

```python
Error running event handler:
Traceback (most recent call last):
  File "opdef:/hammer::Sop/group_expand::1.0?ViewerStateModule", line 1, in <module>
ImportError: No module named universal_state

Error running event handler:
Traceback (most recent call last):
  File "opdef:/hammer::Sop/group_expand::1.0?ViewerStateInstall", line 1, in <module>
  File "C:/PROGRA~1/SideFX/HOUDIN~1.355/houdini/python2.7libs\viewerstate\utils.py", line 1099, in register_pystate_embedded
    template = node_type.hdaViewerStateModule().createViewerStateTemplate()
  File "C:/PROGRA~1/SideFX/HOUDIN~1.355/houdini/python2.7libs\hou.py", line 39278, in __getattr__
    def __getattr__(*args): return _hou.HDAViewerStateModule___getattr__(*args)
AttributeError: 'module' object has no attribute 'createViewerStateTemplate'

```

Thanks,
-MH

**Comment by ivantitov-zd** [comment]
Oh, I'm sorry that I noticed your problem only now. Fixed in the dev branch.
