### ISSUE TITLE
Previous Files: Opening projects with Cyrillic characters in path

### ISSUE THREAD

**Issue by ivantitov-zd** [anvdev/Hammer-Tools#220]
Request from Vladyslav Lavrenov.

**Comment by ivantitov-zd** [comment]
Error in `hou` module.
```py
Traceback (most recent call last):
  File "C:/Users/MarkWilson/Documents/Hammer-Tools/python2.7libs\hammer_tools\previous_files.py", line 176, in __call__
    self.logEvent(hou.hipFile.path(), SessionWatcher.EventType.Save)
  File "D:/HOUDIN~1.556/houdini/python2.7libs\hou.py", line 40187, in path
    return _hou.hipFile_path(*args)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf0 in position 3: invalid continuation byte
```

**Comment by ivantitov-zd** [comment]
From Vladyslav:
Houdini: 18.0.597
OS: Windows 10
![image](https://user-images.githubusercontent.com/28631927/111175283-14930700-85ca-11eb-859c-71ffe7698b5f.png)
Recent files can open this file.
